language: cpp
compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libbullet-dev libboost-test-dev

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V
