language: cpp
sudo: required
dist: trusty
cache: ccache
compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-test-dev

install:
    - git clone https://github.com/bulletphysics/bullet3.git
    - mkdir bullet-build
    - cd bullet-build
    - cmake ../bullet3 -G "Unix Makefiles" -DUSE_GRAPHICAL_BENCHMARK=OFF -DBUILD_CPU_DEMOS=OFF -DUSE_GLUT=OFF -DBUILD_BULLET3=OFF -DBUILD_BULLET2_DEMOS=OFF -DBUILD_EXTRAS=OFF -DBUILD_UNIT_TESTS=OFF
    - make -j4
    - sudo make install

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - ctest -V
