language: cpp
sudo: required
dist: trusty
cache: ccache
compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-test-dev

install:
    - git clone https://github.com/bulletphysics/bullet3.git
    - cd bullet3/build3
    - ./premake4_linux gmake
    - cd gmake
    - make && sudo make install

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V
